backend:
  name: github
  repo: fuyakai/blog.xspeedup.com
  branch: master
  base_url: https://blog.xspeedup.com
  auth_endpoint: /api/auth

local_backend: false

publish_mode: editorial_workflow

media_folder: "src/assets"
public_folder: "../../assets"

site_url: https://blog.xspeedup.com
display_url: https://blog.xspeedup.com
logo_url: https://blog.xspeedup.com/favicon.svg

locale: zh_Hans

collections:
  - name: "blog"
    label: "博客文章"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "描述", name: "description", widget: "string" }
      - { label: "发布日期", name: "pubDate", widget: "datetime", format: "MMM DD YYYY", date_format: "MMM DD YYYY", time_format: false }
      - { label: "更新日期", name: "updatedDate", widget: "datetime", required: false, format: "MMM DD YYYY", date_format: "MMM DD YYYY", time_format: false }
      - { label: "封面图", name: "heroImage", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
